server:
    port: 8080

server.context-path:

# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: false
security.basic.enabled: false


asyncapi:
    restHttpPoolMaxTotal: 30
    restHttpPoolMaxPerRoute: 20
    restHttpPoolTimeout: 10000
    restHttpTimeout: 10000

    service:
      timeout: 5000
      pollingTimeout: 100

      internal:
        callback:
          url: http://localhost:4080/backend-service/method
          ignoreExceptions: false

    cacheConfName: ehcache.xml
